set nocompatible
source $VIMRUNTIME/vimrc_example.vim
"source $VIMRUNTIME/mswin.vim
"behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let eq = ''
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      let cmd = '""' . $VIMRUNTIME . '\diff"'
      let eq = '"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction

set nobackup
set nowritebackup
set noundofile

"set guifont="Lucida_Console:h11,Monospace:h12"

"execute pathogen#infect()
syntax on
filetype plugin indent on

if has("gui_running")
  if has("gui_gtk2")
    set guifont=Inconsolata\ 12
  elseif has("gui_macvim")
    set guifont=Menlo\ Regular:h14
  elseif has("gui_win32")
    set guifont=Consolas:h11:cANSI
  endif
endif

set number
set ruler
nnoremap <C-S-tab> :tabprevious<CR>
nnoremap <C-tab>   :tabnext<CR>
nnoremap <C-t>     :tabnew<CR>
inoremap <C-S-tab> <Esc>:tabprevious<CR>i
inoremap <C-tab>   <Esc>:tabnext<CR>i
inoremap <C-t>     <Esc>:tabnew<CR>

vnoremap y ygv
"clipboard
if has("clipboard")
    vnoremap <C-c> "+ygv
    vnoremap <C-v> "+p
    nnoremap <C-Space> gg"+yG<C-o><C-o>
    nnoremap <C-c> "+y
    nnoremap <C-c><C-c> "+yy
endif

inoremap <C-]> <ESC>

"INDENTATION
set expandtab
set shiftwidth=4
set softtabstop=4

nnoremap ZZ :wqall<Enter>

"PLUGINS
helptags ALL

"ALE
let g:ale_sign_column_always = 1
let g:airline#extensions#ale#enabled = 1
let g:ale_open_list = 1
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)

"NERDTree
let NERDTreeShowHidden=1
autocmd vimenter * NERDTree | wincmd w

"YCM
let g:ycm_python_binary_path = '/usr/bin/python3'
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_autoclose_preview_window_after_insertion = 1


"Utils
command Py2 execute "let g:ycm_python_binary_path = '/usr/bin/python2'"
command Py3 execute "let g:ycm_python_binary_path = '/usr/bin/python3'"
Py3

"coisa linda
colorscheme mac_classic

set wildmenu
set wildmode=longest,full
filetype plugin on
set omnifunc=syntaxcomplete#Complete
